services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:3000 "fileuploader.app:create_app()"
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
      - ./clipboard:/app/clipboard
    ports:
      - "3020:3000"
    environment:
      - FLASK_ENV=production
      - UPLOAD_FOLDER=/app/uploads
      - CLIPBOARD_FOLDER=/app/clipboard
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
